version: "3.1"
services:
    mariadb:
      image: mariadb:10.4
      container_name: bicicletas-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=bicicletas
        - MYSQL_USER=demo
        - MYSQL_PASSWORD=demo
      ports:
        - "8086:3306"

    webserver:
      image: nginx:alpine
      container_name: bicicletas-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8083:80"

    php-fpm:
      build: docker/php-fpm
      container_name: bicicletas-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

